# C/C++ with GCC
# Build your C/C++ project with GCC using make.
# Add steps that publish test results, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/c-cpp/gcc

trigger:
  - master

pool:
  vmImage: 'vs2017-win2016'

variables:
  url: https://ufpr.dl.sourceforge.net/project/cbp2make/cbp2make-stl-rev147-all.tar.7z
  fileName: cbp2make.tar.7z

steps:
  - task: PythonScript@0
    displayName: 'Download cbp2make'
    inputs:
      scriptSource: 'inline'
      script: from urllib.request import urlretrieve; urlretrieve('$(url)', '$(fileName)')

  - task: ExtractFiles@1
    inputs:
      archiveFilePatterns: $(Build.SourcesDirectory)/$(fileName)
      destinationFolder: $(Build.SourcesDirectory)
      cleanDestinationFolder: false

  - script: |
      cbp2make-stl-rev147-all\bin\Release\cbp2make.exe -in sistema_de_veiculo.cbp -out Makefile -windows
    displayName: 'Generate Makefile'
  - script: |
      make all
    displayName: 'Build'
  - task: CopyFiles@2
    displayName: 'Copy'
    inputs:
      contents: 'bin\Release\*.exe'
      targetFolder: $(Build.ArtifactStagingDirectory)

  - task: GithubRelease@0
    displayName: 'Create GitHub Release'
    inputs:
      gitHubConnection: GithubRodrigo54
      repositoryName: Rodrigo54/sistema_de_veiculos
      tagSource: manual
      tag: $(Build.BuildNumber)
      assets: |
        $(Build.ArtifactStagingDirectory)/bin/Release/*.exe
        $(Build.ArtifactStagingDirectory)/README.txt